# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IMAP-SimpleX-SSL
version:      0.1
version_from: lib/Net/IMAP/SimpleX/SSL.pm
installdirs:  site
requires:
    IO::Socket::SSL:               
    Net::IMAP::SimpleX:             0.95
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
